<div class="sidebox">
    <h2>Giới thiệu</h2>
    <div class="vmenu">
        <ul>
            <li>
                ĐỒ ÁN UDPT - Chợ Online 
            </li>
            <li>
                18120553 - Nguyễn Lê Ngọc Tần
            </li>
            <li>
                18120560 - Lê Hữu Thanh
            </li>
            <li>
                18120570 - Nguyễn Thanh Thi
            </li>
            <li>
                18120590 - Lê Viết Tiến
            </li>
        </ul>
    </div>

</div>

<div class="sidebox">  
    <h2> ĐI CHỢ ONLINE </h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="index.php"> <b> Trang chủ </b> </a>
            </li>
            <li>
                <a href="?action=login"> Đăng nhập/Đăng xuất </a>
            </li>    
            <li>
                <a href="?action=perioddemand"> Nhu cầu thực phẩm cùng kỳ</a>
            </li>
            <li>
                <a href="?action=contact"> Liên hệ </a>
            </li>        
        </ul>
    </div>
    <h2>KHÁCH HÀNG</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="?action=listallproductofsupplier"> Tìm sản phẩm </a>
            </li>
            <li>
                <a href="?action=addaccount"> Đăng ký tài khoản </a>
            </li>            
            <li>
                <a href="#"> Giỏ hàng </a>
            </li>
            <li>
                <a href="?action=purchasinghistory"> Lịch sử mua hàng </a>
            </li>

            <li>
                <a href="?action=listdonhang"> Quản lý đơn hàng </a>
            </li>
            <li>
                <a href="?action=listphanhoi"> Phản hồi </a>
            </li>

        </ul>
    </div>
    <h2>NHÀ CUNG ỨNG</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="?action=topproduct"> Thống kê mặt hàng bán chạy </a>
            </li>
            <li>
                <a href="?action=turnover"> Thu nhập </a>
            </li>   
            <li>
                <a href="#"> Thêm sản phẩm </a>
            </li>         
        </ul>
    </div>
    <h2>ĐƠN VỊ VẬN CHUYỂN</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="?action=deliveryhistory"> Lịch sử giao hàng </a>
            </li> 
            <li>
                <a href="?action=confirmorder"> Tiếp nhận đơn hàng </a>
            </li>
            <li>
                <a href="?action=deliveryconfirmation"> Xác nhận giao hàng</a>
            </li>

        </ul>
    </div>
    <h2>ADMIN</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="?action=listsupplier"> Xem DS Nhà cung ứng </a>
            </li>
            <li>
                <a href="?action=listtransport"> Xem DS Đơn vị vận chuyển </a>
            </li>   
            <li>
                <a href="?action=addsupplier"> Thêm Nhà cung ứng </a>
            </li> 
            <li>
                <a href="?action=addtransport"> Thêm Đơn vị vận chuyển </a>
            </li>  
            <li>
                <a href="?action=showtoaddshipper"> Thêm Shipper </a>
            </li>      
        </ul>
    </div>
</div>