<script type="text/javascript">
    function check()
    {
        if (document.getElementById("TenShipper").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập tên shipper!</b></i>";
            return false;
        }

        if (document.getElementById("SDT").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập SĐT!</b></i>";
            return false;
        }

        if (document.getElementById("Email").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập Email!</b></i>";
            return false;
        }

        if (document.getElementById("DiaChi").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập địac chỉ!</b></i>";
            return false;
        }

        if (document.getElementById("TaiKhoan").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Chọn tài khoản Login của bạn!</b></i>";
            return false;
        }

        if (document.getElementById("CMND").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập CMND!</b></i>";
            return false;
        }

        if (document.getElementById("NgaySinh").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập ngày sinh!</b></i>";
            return false;
        }

        if (document.getElementById("MaDVVC").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Chọn DVVC</b></i>";
            return false;
        }

        return true;
    }
</script>

<h1>CẬP NHẬT SHIPPER: <?php echo $shipper->TenShipper; ?></h1>
<hr/>

 <form method ="POST" onsubmit="return check();">
 	<input type="hidden" name="action" value="updateshipper" />
     <table>
        <tr>
            <td>Mã Shipper </td>
            <td><input id="MaShipper" name="maShipper" type="text" value="<?php echo $shipper->MaShipper ?>" disabled/></td>
        </tr>
        <tr>
            <td>Tên Shipper </td>
            <td><input id="TenShipper" name="tenShipper" type="text" value="<?php echo $shipper->TenShipper ?>" /></td>
        </tr>
        <tr>
            <td>Giới tính</td>
            <td><input id="GioiTinh" name="gioiTinh" type="text" value="<?php echo $shipper->GioiTinh ?>"/></td>                   
        </tr>
        <tr>
            <td>SĐT</td>
            <td><input id="SDT" name="sdt" type="text" value="<?php echo $shipper->SDT ?>"/></td>
        </tr>
        <tr>
            <td>Địa chỉ</td>
            <td><input id="DiaChi" name="diaChi" type="text" value="<?php echo $shipper->DiaChi ?>"/></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input id="Email" name="email" type="text" value="<?php echo $shipper->Email ?>"/></td>
        </tr>
        <tr>
            <td>CMND</td>
            <td><input id="CMND" name="cmnd" type="text" value="<?php echo $shipper->CMND ?>" /></td>
        </tr> 
        <tr>
            <td>Ngày sinh</td>
            <td><input id="NgaySinh" name="ngaySinh" type="text" value="<?php echo $shipper->NgaySinh ?>" /></td>
        </tr>  
        <tr>
            <td>Đơn vị vận chuyển</td>
            <td>
                <select name="maDVVC" class="maDVVC" id="MaDVVC" value="<?php echo $shipper->MaDVVC ?>">
                    <?php
                        foreach ($dsDVVC as $item)
                        {
                            ?>
                                <option value='<?php echo $item->MaDVVC; ?>'>
                                    <?php echo $item->MaDVVC; ?> 
                                </option>
                            <?php
                        }
                    ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>Tài khoản</td>
            <td><input id="TaiKhoan" name="taiKhoan" type="text" value="<?php echo $shipper->TaiKhoan ?>" /></td>
        </tr>    
        <tr>
            <td>Xét duyệt</td>
            <td>
                <select name="xetDuyet" class="xetDuyet" id="xetDuyet" value="<?php echo $shipper->XetDuyet ?>">
                    <option value='1'>1</option>
                    <option value='0'>0</option>
                </select>
            </td>
        </tr>            
    </table>
    <input type="submit" value="updateshipper" style="width: 200px; margin-left:200px; margin-top:20px;"/> 
    <br/><br/>
    <span id="message"> </span>
</form>

<script>
    window.onload = function(){
        document.getElementById("MaDVVC").value = <?php echo $shipper->MaDVVC ?>;
        document.getElementById("xetDuyet").value = <?php echo $shipper->XetDuyet ?>;
    }
</script>
    