<?php
	if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
?>
<?php
	if (!isset ($_SESSION["IsLogined"]) || $_SESSION["IsLogined"] != true || (isset ($_SESSION["VaiTro"]) && $_SESSION["VaiTro"] != "ADMIN"))
	{
		die ("You are not permitted for using this page !!! Click <a href='?action=login'>here </a> to goto login page ! ");
	}
	$username = $_SESSION["UserName"];
?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
//    function CheckAll(parent)
//     {
//         var ids = document.getElementsByTagName('input');
//         for(var i=0; i<ids.length; i++)
//         {
//             if(ids[i].name == "checkbox[]")
//             {
//                 ids[i].checked = parent.checked;
//             }
// 	    }
//     }
</script>

<h3>DANH SÁCH CÁC ĐƠN VỊ VẬN CHUYỂN</h3>
<form class="form-table" method="post">
<input type="hidden" name="action" value="deleteAllTransportCheckedBox" />
<div class="form-table">
    <table class="empty-table">
        <thead>
            <tr>
                <!-- <th>
                    <input name="allbox" type="checkbox" id="allbox" value="All" onclick="CheckAll(this)"/>
                    <i>CheckAll</i>
                </th> -->
                <th>Mã</th>
                <th>Tên DVVC</th>
                <th style="width:50px;">Giấy phép kinh doanh</th>
                <th>SDT</th>
                <th>Địa chỉ</th>
                <th>Email</th>
                <th style="width:50px;">Phí vận chuyển/KM</th>
                <th>Xét duyệt</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 9;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 9)
                $limit = $start + 9;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $dvvc = new DonViVanChuyenModel();
                $dvvc = $data[$i];
                $result[] = $dvvc;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <!-- <td>
                                <input id="checkbox" name="checkbox[]" type="checkbox" value='<?php echo $item->MaDVVC; ?>'/>    
                            </td> -->
                            <td><?php echo $item->MaDVVC; ?></td>
                            <td><?php echo $item->TenDVVC; ?></td>
                            <td><?php echo $item->GiayPhepKinhDoanh; ?></td>
                            <td><?php echo $item->SDT; ?></td>
                            <td><?php echo $item->DiaChi; ?></td>
                            <td><?php echo $item->Email; ?></td>
                            <td><?php echo $item->PhiVanChuyen_KM; ?></td>
                            <td><?php if  ($item->XetDuyet === 0) echo "Chưa duyệt"; else echo "Đã duyệt"; ?></td>
                            <td>
                                <ul>
                                    <li>
                                        <a href="?action=listshipper&madvvc=<?php echo $item->MaDVVC; ?>">DS_Shipper</a>
                                    </li>
                                    <li>
                                        <a href="?action=showtoupdatetransport&madvvc=<?php echo $item->MaDVVC; ?>">Update</a>
                                    </li>
                                    <li>
                                        <a href="?action=deletetransport&madvvc=<?php echo $item->MaDVVC; ?>">Delete</a> 
                                    </li>
                                    <li>
                                        <a href="?action=accepttransport&madvvc=<?php echo $item->MaDVVC; ?>">Accept</a>
                                    </li>
                                </ul>
                            </td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=listtransport&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=listtransport&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=listtransport&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=listtransport&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=listtransport&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
    <br/><br/><br/>
    <!-- <input type="submit" value="deleteAllTransportCheckedBox" style="width: 200px;"/> -->
</div>
</form>