

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
    // function CheckAll(parent)
    // {
    //     var ids = document.getElementsByTagName('input');
    //     for(var i=0; i<ids.length; i++)
    //     {
    //         if(ids[i].name == "checkbox[]")
    //         {
    //             ids[i].checked = parent.checked;
    //         }
	//     }
    // }
</script>

<h3>DANH SÁCH CÁC SHIPPER CỦA "<?php echo $transportObject->TenDVVC; ?>"</h3>
<form method="POST">
<input type="hidden" name="action" value="deleteAllShipperCheckedBox" />
<div>
    <table class="empty-table">
        <thead>
            <tr>
                <!-- <th>
                    <input name="allbox" type="checkbox" id="allbox" value="All" onclick="CheckAll(this)"/>
                    <i>CheckAll</i>
                </th> -->
                <th>Mã</th>
                <th>Tên Shipper</th>
                <th>SDT</th>
                <th>Giới tính</th>
                <th>Địa chỉ</th>
                <th>Email</th>
                <th>CMND</th>
                <th>Ngày sinh</th>
                <th>Xét duyệt</th>
                <th style="width:80px;"></th>
            </tr>
        </thead>
        <tbody>
            <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 9;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 9)
                $limit = $start + 9;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $s = new ShipperModel();
                $s = $data[$i];
                $result[] = $s;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <!-- <td>
                                <input name="checkbox[]" type="checkbox" value='<?php echo $item->MaShipper; ?>'/>    
                            </td> -->
                            <td><?php echo $item->MaShipper; ?></td>
                            <td><?php echo $item->TenShipper; ?></td>
                            <td><?php echo $item->SDT; ?></td>
                            <td><?php echo $item->GioiTinh; ?></td>
                            <td><?php echo $item->DiaChi; ?></td>
                            <td><?php echo $item->Email; ?></td>
                            <td><?php echo $item->CMND; ?></td>
                            <td><?php echo $item->NgaySinh; ?></td>
                            <td><?php if ($item->XetDuyet === 0) echo "Chưa duyệt"; else echo "Đã duyệt"; ?></td>
                            <td> 
                                <li>
                                    <a href='?action=deleteshipper&mashipper=<?php echo $item->MaShipper; ?>'>Delete</a>
                                </li>
                                <li>
                                    <a href='?action=showtoupdateshipper&mashipper=<?php echo $item->MaShipper; ?>'>Update</a>
                                </li>
                                <li>
                                    <a href='?action=acceptshipper&mashipper=<?php echo $item->MaShipper; ?>'>Accept</a>
                                </li>
                                
                            </td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=listshipper&madvvc='.($madvvc).'&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=listshipper&madvvc='.($madvvc).'&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            if ($current_page + 2 <= $total_page)
            {
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=listshipper&madvvc='.($madvvc).'&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }}
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=listshipper&madvvc='.($madvvc).'&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=listshipper&madvvc='.($madvvc).'&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
    <br/><br/><br/>
    <!-- <input type="submit" value="deleteAllShipperCheckedBox" style="width: 200px;"/> -->
</div>
</form>