

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
//    function CheckAll(parent)
//     {
//         var ids = document.getElementsByTagName('input');
//         for(var i=0; i<ids.length; i++)
//         {
//             if(ids[i].name == "checkbox[]")
//             {
//                 ids[i].checked = parent.checked;
//             }
// 	    }
//     }
</script>

<h3>DANH SÁCH SẢN PHẨM CỦA NHÀ CUNG ỨNG: <?php echo $supplier->TenNCC; ?></h3>
<form class="form-table">
<div class="form-table">
    <table class="empty-table">
        <thead>
            <tr>
                <!-- <th>
                    <input name="allbox" type="checkbox" id="allbox" value="All" onclick="CheckAll(this)"/>
                    <i>CheckAll</i>
                </th> -->
                <th>Mã SP</th>
                <th>Tên SP</th>
                <th>Đơn vị tính</th>
                <th>NSX</th>
                <th>Gía bán</th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 10;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 10)
                $limit = $start + 10;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $ncc = new NhaCungCapModel();
                $ncc = $data[$i];
                $result[] = $ncc;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <!-- <td>
                                <input id="checkbox" name="checkbox[]" type="checkbox" value='<?php echo $item->ID; ?>'/>    
                            </td> -->
                            <td><?php echo $item->MaSP; ?></td>
                            <td><?php echo $item->TenSP; ?></td>
                            <td><?php echo $item->DonViTinh; ?></td>
                            <td><?php echo $item->NSX; ?></td>
                            <td><?php echo $item->Gia; ?></td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=listproductofsupplier&mancc='.($supplier->MaNCC).'&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=listproductofsupplier&mancc='.($supplier->MaNCC).'&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=listproductofsupplier&mancc='.($supplier->MaNCC).'&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=listproductofsupplier&mancc='.($supplier->MaNCC).'&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=listproductofsupplier&mancc='.($supplier->MaNCC).'&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
    <br/><br/><br/>
</div>
</form>