
<h3>DANH SÁCH PHẢN HỒI <form> <input type="hidden" name="action" value="showtophanhoi" >
    <input type="submit" value ="Thêm phản hồi" ></input> 
</form>
</h3>


<form class="form-table" method="post">

<div class="form-table">
    <table class="empty-table">
        <thead>
            <tr>
                <!-- <th>
                    <input name="allbox" type="checkbox" id="allbox" value="All" onclick="CheckAll(this)"/>
                    <i>CheckAll</i>
                </th> -->
                <th>Mã</th>
                <th>Chi tiết</th>                
                <th>Thời gian</th>
                <th>ID Người tạo</th>
                <th>ID Sản phẩm</th>
                <th>ID Nhà cung cấp</th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->

        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 9;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 9)
                $limit = $start + 9;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $PH = new PhanhoiModel();
                $PH = $data[$i];
                $result[] = $PH;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            
                            <td><?php echo $item->maphanhoi; ?></td>
                            <td><?php echo $item->chitiet; ?></td>
                            <td><?php echo $item->ngaytao; ?></td>
                            <td><?php echo $item->nguoidung; ?></td>
                            <td><?php echo $item->sanpham; ?></td>
                            <td><?php echo $item->nhacungcap; ?></td>                            
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=listphanhoi&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=listphanhoi&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=listphanhoi&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=listphanhoi&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=listphanhoi&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
    <br/><br/><br/>
    <!-- <input type="submit" value="deleteAllTransportCheckedBox" style="width: 200px;"/> -->
</div>
</form>