<?php
	if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
?>
<?php
	if (!isset ($_SESSION["IsLogined"]) || $_SESSION["IsLogined"] != true || (isset ($_SESSION["VaiTro"]) && $_SESSION["VaiTro"] != "DVVC"))
	{
		die ("You are not permitted for using this page !!! Click <a href='?action=login'>here </a> to goto login page ! ");
	}
	$username = $_SESSION["UserName"];
?>


<?php
if (!function_exists('currency_format')) {
    function currency_format($number, $suffix = 'đ') {
        if (!empty($number)) {
            return number_format($number, 0, ',', '.') . "{$suffix}";
        }
    }
}
?>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<h3>LỊCH SỬ GIAO HÀNG CỦA ĐƠN VỊ VẬN CHUYỂN : <?php echo $dvvc->TenDVVC;?></h3>
<form class="form-table">

<div class="form-table">
    <table class="empty-table">
        <thead>
            <tr>
                <th style="width:30px;">Mã ĐH</th>
                <th>Ngày lập</th>
                <th>Tên khách hàng</th>
                <th>Địa chỉ</th>
                <th>Số điện thoại khách hàng</th>
                <th style="width:30px;">Mã Shipper</th>
                <th>Tên Shipper</th>
                <th>Tên đơn vị vận chuyển</th>
                <th>Trạng thái</th>
                <th>Hình thức thanh toán</th>
                <th>Tổng tiền</th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 10;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 10)
                $limit = $start + 10;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $p = new LichSuGiaoHangModel();
                $p = $data[$i];
                $result[] = $p;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <td><?php echo $item->MaDH; ?></td>
                            <td><?php echo $item->NgayLap; ?></td>
                            <td><?php echo $item->TenKH; ?></td>
                            <td><?php echo $item->DiaChi; ?></td>
                            <td><?php echo $item->SDTKhachHang; ?></td>
                            <td><?php echo $item->MaShipper; ?></td>
                            <td><?php echo $item->TenShipper; ?></td>
                            <td><?php echo $item->TenDVVC; ?></td>
                            <td><?php echo $item->TrangThai; ?></td>
                            <td><?php echo $item->HinhThucThanhToan; ?></td>
                            <td><?php echo currency_format($item->TongTien); ?></td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=deliveryhistory&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=deliveryhistory&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=deliveryhistory&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=deliveryhistory&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=deliveryhistory&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
</div>
</form>
<br/><br/><br/><br/><hr/><br/><br/>




