<h1>THÔNG TIN LIÊN HỆ</h1>
<hr/>
<div class="row">
    <div class="column">
        <div class="card">
            <img src=".\css\images\avatar\18120553.png" alt="Tan" style="width:100%">
            <div class="container">
                <h3>Nguyễn Lê Ngọc Tần</h3>
                <p class="title">Information System</p>
                <p class="title">MSSV: 18120553</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
   </div>
 
   <div class="column">
        <div class="card">
            <img src=".\css\images\avatar\18120560.png" alt="Thanh" style="width:100%">
            <div class="container">
                <h3>Lê Hữu Thanh</h3>
                <p class="title">Information System</p>
                <p class="title">MSSV: 18120560</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
   </div>

   <div class="column">
        <div class="card">
            <img src=".\css\images\avatar\18120570.png" alt="Thi" style="width:100%">
            <div class="container">
                <h3>Nguyễn Thanh Thi</h3>
                <p class="title">Information System</p>
                <p class="title">MSSV: 18120570</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
   </div>

   <div class="column">
        <div class="card">
            <img src=".\css\images\avatar\18120590.png" alt="Tien" style="width:100%">
            <div class="container">
                <h3>Lê Việt Tiến</h3>
                <p class="title">Information System</p>
                <p class="title">MSSV: 18120590</p>
                <p><button class="button">Contact</button></p>
            </div>
        </div>
   </div>
  
 </div>