<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<h3>Đăng nhập</h3>

<form method ="post">
 	<input type="hidden" name="action" value="login" />
    <table>
        <tr>
            <td>Username</td>
            <td>
                <input name="username" type="text" value=""/>
            </td>
        </tr>
        <tr>
            <td>Password</td>
            <td>
                <input style="width:275px; height:30px" name="password" type="password" value=""/>
            </td>                   
        </tr>
    </table>
    <input type="submit" value="login" style="width: 150px;"/>
    <?php


        // if (isset ($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True)
        // {			
        //     if (isset($_SESSION["name"]))	
        //     {
        //         $name = $_SESSION["name"];
        //         echo "Logined user: $name <a href=\"?action=logout\"> sign out </a>";
        //     }
        // }



        if (isset ($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True)
        {				
            $username = $_SESSION["UserName"];
            echo "<br/><br/>Logined user: \"" . $username ."\" ===> <a href='?action=logout'> sign out </a>";
        }
        else
        {
            echo "<br/><br/><i>Anonymous user</i><br/><br/>";

        }
    ?>
</form>