<?php
	if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
?>
<?php
	if (!isset ($_SESSION["IsLogined"]) || $_SESSION["IsLogined"] != true || (isset ($_SESSION["VaiTro"]) && $_SESSION["VaiTro"] != "DVVC"))
	{
		die ("You are not permitted for using this page !!! Click <a href='?action=login'>here </a> to goto login page ! ");
	}
	$username = $_SESSION["UserName"];
?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
</script>

<h3>DANH SÁCH CÁC ĐƠN HÀNG CHỜ TIẾP NHẬN </h3>
<form class="form-table" method="post">
<div class="form-table">
    <table class="empty-table">
        <thead>
            <tr>
                <th>Mã đơn hàng</th>
                <th style="width:100px;">Ngày lập</th>
                <th style="width:50px;">Tổng tiền</th>
                <th>Trạng thái</th>
                <th style="width:70px;">Mã khách hàng</th>
                <th>Hình thức thanh toán</th>
                <th style="width:50px;">Mã nhân viên giao hàng</th>
                
                <th style="width:80px;"></th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 9;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 9)
                $limit = $start + 9;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $dh = new DonHangModel();
                $dh = $data[$i];
                $result[] = $dh;
            }

        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <!-- <td>
                                <input id="checkbox" name="checkbox[]" type="checkbox" value='<?php echo $item->MaDH; ?>'/>    
                            </td> -->
                            <td><?php echo $item->MaDH; ?></td>
                            <td><?php echo $item->NgayLap; ?></td>
                            <td><?php echo $item->TongTien; ?></td>
                            <td><?php echo $item->TrangThai; ?></td>
                            <td><?php echo $item->MaKH; ?></td>
                            <td><?php echo $item->HinhThucThanhToan; ?></td>
                            <td><?php echo $item->MaShipper; ?></td>
                            <td>
                                <a href="?action=showtoconfirmorder&madh=<?php echo $item->MaDH; ?>">Cập nhật</a>
                            </td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=confirmorder&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=confirmorder&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=confirmorder&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=confirmorder&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=confirmorder&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
    <br/><br/><br/>
    <!-- <input type="submit" value="deleteAllSupplierCheckedBox" style="width: 200px;"/> -->
</div>
</form>